# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Bekasi Timur Revival 2022"
email: "info@bekasitimurrevival.id"
description: "Kebaktian Kebangunan Rohani Bekasi Timur 2022"
baseurl: "/zeppelin"
url: "https://btcr18.github.io"
# permalink: "/blog/:title"

# Organizer Info
organizerName: "GBI BTC Rayon 18"
organizerAlternateName: "GBI BTC Rayon 18"
organizerDescription: "Christian revivalism is increased spiritual interest or renewal in the life of a church congregation or society, with a local, national or global effect. This should be distinguished from the use of the term _revival_ to refer to an evangelistic meeting or series of meetings"
organizerEmail: "info@bekasitimurrevival.id"
# organizerLogo: "/img/seo/organizer-logo.png"
organizerLogo: "/img/seo/bekasitimurrevival_logo.png"
organizerLink: "https://bekasitimurrevival.id"

# https://github.dev/btcr18/zeppelin/blob/gh-pages/img/seo/bekasitimurrevival_logo.png

# Head
metaKeywords: "KKR, BEKASI, BEKASITIMUR, BTC, GBI, GEREJA, KEBAKTIAN, PEMULIHAN, KESEMBUHAN, HEALING, JESUS"
twitterAccount: "@bekasitimurrevival.id"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Jadwal"}
 - {permalink: "/speakers/", text: "Penampilan"}
bottomNavigationLinks:
 - {link: "https://s.id/bekasitimurrevival", text: "Daftar Sekarang"}
rightNavigationButtons:
 - {link: "https://s.id/bekasitimurrevival", text: "Daftar Sekarang"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "BEKASI TIMUR REVIVAL - <typeout> "
eventDate: "16 Desember 2022, 18.00 - 20.00"
typeoutTextValues: '"KUASA", "PUJIAN", "PENYEMBAHAN", "PENGURAPAN", "KESEMBUHAN"'
typeoutFallback: "KKR"
heroButtons:
 - {link: "https://s.id/bekasitimurrevival", text: "Daftar Sekarang"}

# About Block
aboutTitle: "Kebaktian Kebangunan Rohani Bekasi Timur 2022"
aboutBlock:
 - {title: "KKR", image: "conference.jpg", text: "Pembicara KKR Natal GBI BTC Rayon 18 merupakan Gembala GBI Rayon 18, yaitu Pdt. Andy Markus. Beliau mendapatkan tuntunan yaitu To Bless The City yang kemudian mengalami transformasi menjadi To Bless The Nations. Dalam perjalanan Visi besar GBI Rayon 18, Pdt. Andy Markus mendapatkan tuntunan untuk fokus kepada 2 hal yaitu Pastoral/Penggembalaan dan Pendidikan." }
#  - {title: "KKR", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
#  - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
#  - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "Peserta KKR", detail: "Dari Segala Penjuru Bekasi Timur"}
 - {count: "2", specialCharacter: "+", info: "Jam", detail: "Lawatan dalam Pujian, Penyembahan dan Doa"}
 - {count: "3", specialCharacter: "+", info: "Penampil Kesaksian", detail: "Artis Rohani Kristen"}

# # Latest News Block
# latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Penampilan Kesaksian KKR"
rockstarSpeakersButtonText: "Lihat Detail"

# Location Block
locationBlockTitle: "Lokasi"
eventLocationName: "GBI BTC Rayon 18"
eventLocationLink: "https://goo.gl/maps/GGHk2cKwtdHPdVJY9"
eventStreetAddress: "Jl. HM. Joyo Martono No.30"
eventAddressLocality: "Bekasi Timur"
eventAddressLocalityRegion: "Kota Bekasi"
eventPostalCode: "17113"
eventAddressCountry: "Indonesia"
eventStartTime: "2022-12-16T07:00"
eventDoorTime: "18:30"
eventEndTime: "2022-12-16T07:00"
eventPlaceCoordinates: "-6.258010076377598, 107.02185204602647"
mapCenterCoordinates: "-6.258010076377598, 107.02185204602647"
mapMobileCenterCoordinates: "-6.258010076377598, 107.02185204602647"

# Venue Block
venueBlockTitle: "Lokasi:"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "GBI BTC Rayon 18"
venueFeatures: ["Terletak dekat dengan pintu Tol Bekasi Timur"]

# # Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "KKR-NATAL-GBI-BTC-RAYON-18"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# # Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a sponsor"

# # Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# # Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers:
#  -
#   name: "Early Bird"
#   price: "350"
#   priceCurrency: "UAH"
#   ticketsNumber: "150"
#   ribbon: "-5%"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: "450"
#   priceCurrency: "UAH"
#   ticketsNumber: "100"
#   ribbon: "-20%"
#   featured: true
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
#  -
#   name: "Student"
#   price: "200"
#   priceCurrency: "UAH"
#   ticketsNumber: "50"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-20T10:00"
#   validThrough: "2014-10-23T23:59"
#   soldOut: true
#   soldOutText: "Sold Out"

# Footer
socialLinks:
#  - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
#  - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://www.facebook.com/people/GBI-BTC-RAYON-18/100075955991728/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
# footerBlocks:
#  -
#   title: "Links"
#   links:
#    - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
#    - {link: "https://developers.google.com", text: "Google Developers"}
#  -
#   title: "Contacts"
#   links:
#    - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
#  -
#   title: "FAQ"
#   links:
#    - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# # Speakers List Block
# showSessions: true

# # Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# # Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
